# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeedsparser', '0002_auto_20180829_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='source',
            field=models.CharField(choices=[(b'NONE', b'No sources configured')], default=(b'NONE', b'No sources configured'), max_length=50, verbose_name='Social media'),
        ),
    ]
